paths:
  collections: content
  data: data
  static: public
  uploads: public/images
collections_config:
  data:
    path: data/
    disable_add: true
    disable_add_folder: true
  pages:
    path: content
    glob:
      - content/*.md
    url: '/[full_slug]/'
    output: true
    icon: wysiwyg
    _enabled_editors:
      - visual
    schemas:
      page:
        name: New Page
        path: schemas/page.md
_inputs:
  page_description:
    comment: Defaults to the description set in the Site SEO data file
  favicon_icon:
    type: image
    comment: For the shortcut icon meta tag
  faivcon_image:
    type: image
    comment: For the icon meta tag
  canonical_url:
    comment: Defaults to the pages url
  featured_image:
    comment: Defaults to the image set in the Site SEO data file
  open_graph_type:
    comment: Defaults to the type 'website'
  author_twitter_handle:
    comment: Defaults to the twitter site value set in the Site SEO data file
  no_index:
    type: checkbox
    comment: >-
      When selected this removes the page from your sitemap and adds the noindex
      robots meta tag
